### ISSUE TITLE
Node metadata not always available

### ISSUE THREAD

**Issue by cgarwood** [home-assistant-libs/zwave-js-server-python#50]
I've run into a few issues while testing inclusion/exclusion where I receive the following error during inclusion:

```
2021-01-15 21:28:37 ERROR (MainThread) [zwave_js_server] Unexpected error handling {'type': 'event', 'event': {'source': 'node', 'event': 'ready', 'nodeId': 60, 'node': Node(node_id=60)}}
Traceback (most recent call last):
  File "/home/cgarwood/home-assistant/core/venv/lib/python3.8/site-packages/zwave_js_server/client.py", line 292, in _handle_connection
    self.async_handle_message(msg_)
  File "/home/cgarwood/home-assistant/core/venv/lib/python3.8/site-packages/zwave_js_server/client.py", line 110, in async_handle_message
    self.driver.receive_event(event)
  File "/home/cgarwood/home-assistant/core/venv/lib/python3.8/site-packages/zwave_js_server/model/driver.py", line 23, in receive_event
    self.controller.receive_event(event)
  File "/home/cgarwood/home-assistant/core/venv/lib/python3.8/site-packages/zwave_js_server/model/controller.py", line 324, in receive_event
    node.receive_event(event)
  File "/home/cgarwood/home-assistant/core/venv/lib/python3.8/site-packages/zwave_js_server/model/node.py", line 227, in receive_event
    self.emit(event.type, event.data)
  File "/home/cgarwood/home-assistant/core/venv/lib/python3.8/site-packages/zwave_js_server/event.py", line 52, in emit
    listener(data)
  File "/home/cgarwood/home-assistant/core/venv/lib/python3.8/site-packages/zwave_js_server/event.py", line 43, in event_listener
    callback(data)
  File "/home/cgarwood/home-assistant/core/homeassistant/components/zwave_js/__init__.py", line 105, in <lambda>
    "ready", lambda event: async_on_node_ready(event["node"]),
  File "/home/cgarwood/home-assistant/core/homeassistant/components/zwave_js/__init__.py", line 90, in async_on_node_ready
    for disc_info in async_discover_values(node):
  File "/home/cgarwood/home-assistant/core/homeassistant/components/zwave_js/discovery.py", line 134, in async_discover_values
    disc_val = async_discover_value(value)
  File "/home/cgarwood/home-assistant/core/homeassistant/components/zwave_js/discovery.py", line 174, in async_discover_value
    if schema.type is not None and value.metadata.type not in schema.type:
  File "/home/cgarwood/home-assistant/core/venv/lib/python3.8/site-packages/zwave_js_server/model/value.py", line 122, in metadata
    return ValueMetadata(self.data["metadata"])
KeyError: 'metadata'
```

However, it doesn't happen all the time. Might be an upstream issue with zwave-js? Seems like that should exist if the node is firing the `ready` event.

**Comment by marcelveldt** [comment]
Hmmm, as far as I understand, metadata comes from the device specific config files (just like with OZW).
Maybe if there's no device config file, the metadata will not exist ? The server omits any properties that are empty.
@balloob will the server omit values that are considered empty or null ?

If it omits values that are empty (e.g. an empty dictionary) it will explain our null reference here...

**Comment by balloob** [comment]
JSON serializing in JavaScript will remove a key if the value is `undefined`.

**Comment by marcelveldt** [comment]
Fixed in #61

**Comment by marcelveldt** [comment]
I did some more investigating. 
Value's metadata is ONLY present in the initial state. Value added/changed events do not include the metadata, simply because it is an object that is not json serializable. This means we miss the metadata in several situations like value notifications, adding new nodes and nodes being interviewed after startup.

I'll submit a PR to the server project to fix this.

**Comment by marcelveldt** [comment]
I was wrong with my previous assumption. Adding this to the server itself will alter the messages from the original (metadata is not submitted in events).
Getting the ValueMetaData is actually a node command. It is performed in the state creation but not when a new node is added. So if we want the server to be as transparent as possible, we should do the call to get the metadata in the library.

It is very easy to add this to the server (just request the metadata on "value added" and "value notification" events.
Add this to the python lib is a bit more involved as we'll have to convert the handlers to async.
